<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="8" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="40" started-at="2021-05-22T11:28:56Z" finished-at="2021-05-22T11:28:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="40" started-at="2021-05-22T11:28:56Z" finished-at="2021-05-22T11:28:56Z">
      <class name="org.test.IgnoreAndInvocationCount">
        <test-method status="PASS" signature="tc1()[pri:0, instance:org.test.IgnoreAndInvocationCount@1d057a39]" name="tc1" duration-ms="7" started-at="2021-05-22T11:28:56Z" finished-at="2021-05-22T11:28:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:org.test.IgnoreAndInvocationCount@1d057a39]" name="tc3" duration-ms="1" started-at="2021-05-22T11:28:56Z" finished-at="2021-05-22T11:28:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:org.test.IgnoreAndInvocationCount@1d057a39]" name="tc3" duration-ms="1" started-at="2021-05-22T11:28:56Z" finished-at="2021-05-22T11:28:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:org.test.IgnoreAndInvocationCount@1d057a39]" name="tc3" duration-ms="1" started-at="2021-05-22T11:28:56Z" finished-at="2021-05-22T11:28:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:org.test.IgnoreAndInvocationCount@1d057a39]" name="tc3" duration-ms="0" started-at="2021-05-22T11:28:56Z" finished-at="2021-05-22T11:28:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:org.test.IgnoreAndInvocationCount@1d057a39]" name="tc3" duration-ms="1" started-at="2021-05-22T11:28:56Z" finished-at="2021-05-22T11:28:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
        <test-method status="FAIL" signature="tc4()[pri:0, instance:org.test.IgnoreAndInvocationCount@1d057a39]" name="tc4" duration-ms="1" started-at="2021-05-22T11:28:56Z" finished-at="2021-05-22T11:28:56Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
The exception was thrown with the wrong message: expected "Dont do" but got "/ by zero"]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
The exception was thrown with the wrong message: expected "Dont do" but got "/ by zero"
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:71)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1130)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.ArithmeticException: / by zero
at org.test.IgnoreAndInvocationCount.tc4(IgnoreAndInvocationCount.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
... 19 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc4 -->
      </class> <!-- org.test.IgnoreAndInvocationCount -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
